"""Product-name evidence for the FMCG category (``fmcg_v3``).

The category paths of a retailer decide first. When they give no answer, or several
paths disagree, the product name can still carry the evidence: ``lego``, ``tandpasta``
or ``pedigree`` say what a product is even when its category path is missing or
unmapped.

The vocabulary below is an explicit, reviewed list, not a model. It was mined once
from products whose category is already decided by their paths (see notebook 02,
section 9): a word is kept only when at least ``MIN_SUPPORT`` such products carry it
and at least ``MIN_PURITY`` of them agree on one category. On a random hold-out the
kept words agree with the path decision for 98-99% of the products they fire on. A
handful of generic or retailer words that passed the statistics are rejected on
purpose (``STOP_TOKENS``). Nothing is learned at run time, so the Silver build stays
deterministic.

Only Dutch names are read, as for the category paths. A product needs exactly one
category among its firing words; two categories mean no name evidence.
"""

import re
import unicodedata
from collections import Counter, defaultdict
from collections.abc import Iterable

MIN_SUPPORT = 20
MIN_PURITY = 0.98
NAME_TOKEN = re.compile(r"[a-zà-ÿ]{4,}")

# category code -> words that identify it; generated from the mining above.
NAME_KEYWORDS_NL = {
    "alcoholic_beverages": (
        "bacardi",
        "bacardí",
        "beaujolais",
        "cabernet",
        "chablis",
        "chardonnay",
        "chateau",
        "chenin",
        "château",
        "cinsault",
        "crianza",
        "crémant",
        "eristoff",
        "feuillien",
        "filliers",
        "gewurztraminer",
        "grenache",
        "grigio",
        "huiswijn",
        "jenever",
        "johnnie",
        "kriek",
        "lagrange",
        "lalande",
        "lambic",
        "languedoc",
        "lindemans",
        "loire",
        "malbec",
        "merlet",
        "montepulciano",
        "montrose",
        "médoc",
        "pilsener",
        "pinot",
        "pouilly",
        "primitivo",
        "puertas",
        "rhône",
        "riesling",
        "rioja",
        "rivaner",
        "rosato",
        "sancerre",
        "saumur",
        "sauvignon",
        "schlumberger",
        "sherry",
        "shiraz",
        "strongbow",
        "tawny",
        "tempranillo",
        "tequila",
        "torres",
        "trappist",
        "tripel",
        "truffiers",
        "vermouth",
        "vignes",
        "viognier",
        "vodka",
    ),
    "baby_care": (
        "babydoekjes",
        "bambix",
        "drynites",
        "hipp",
        "huggies",
        "maaltijdpotje",
        "naturnes",
        "nutrilon",
        "olvarit",
        "pampers",
    ),
    "bakery": (
        "jacquet",
        "melkbroodjes",
        "toastbrood",
    ),
    "breakfast_cereals": (
        "jordans",
        "ontbijtgranen",
    ),
    "chilled_prepared": (
        "come",
        "délio",
        "sodebo",
    ),
    "coffee_tea": (
        "decaf",
        "douwe",
        "egberts",
        "huisblends",
        "jacqmotte",
        "koffiecups",
        "kruidenthee",
        "lavazza",
        "lungo",
        "nespresso",
        "oplos",
        "oploskoffie",
        "perla",
        "pickwick",
        "pyramides",
        "ristretto",
        "theezakjes",
        "twinings",
    ),
    "confectionery_snacks": (
        "bahlsen",
        "chewing",
        "chio",
        "croky",
        "delacre",
        "dinosaurus",
        "doritos",
        "eitjes",
        "ferrero",
        "freedent",
        "frisk",
        "fruittella",
        "kruidenpastilles",
        "libeert",
        "lindt",
        "lutti",
        "mentos",
        "merci",
        "mignonnette",
        "notenmix",
        "paaseitjes",
        "pringles",
        "snoep",
        "snoepjes",
        "spearmint",
        "stimorol",
        "superchips",
        "verkade",
    ),
    "dairy_eggs": (
        "actimel",
        "activia",
        "arla",
        "babybel",
        "balade",
        "brie",
        "camembert",
        "campina",
        "carlsbourg",
        "cécémel",
        "danio",
        "danone",
        "drinkyoghurt",
        "entremont",
        "galbani",
        "gruyère",
        "kefir",
        "koffiemelk",
        "laitière",
        "melkerijboter",
        "melkunie",
        "milner",
        "oikos",
        "philadelphia",
        "skyr",
        "smeerkaas",
        "vache",
        "vitalinea",
        "yoplait",
        "zuivelhoeve",
    ),
    "fresh_produce": (
        "ijsbergsla",
        "pitloos",
        "vastkokend",
    ),
    "frozen": (
        "belviva",
        "dazs",
        "häagen",
        "ijsboerke",
        "jerry",
        "pint",
        "roomijs",
        "sorbet",
        "wagner",
    ),
    "household_care": (
        "afwasmiddel",
        "ajax",
        "allesreiniger",
        "allin",
        "ambi",
        "ariel",
        "beckmann",
        "bleekwater",
        "bref",
        "carolin",
        "dash",
        "destop",
        "dixan",
        "dreft",
        "duocaps",
        "dweil",
        "ecarlate",
        "febreze",
        "freshmatic",
        "frosch",
        "glorix",
        "harpic",
        "javel",
        "kalkreiniger",
        "lenor",
        "lijnolie",
        "omino",
        "ontvetter",
        "ontvlekker",
        "oppervlakken",
        "parket",
        "persil",
        "powerball",
        "propre",
        "schoensmeer",
        "silan",
        "soupline",
        "stofzuigzak",
        "swiffer",
        "toiletblok",
        "unstoppables",
        "vaatwascapsules",
        "vaatwastabletten",
        "vileda",
        "vlekverwijderaar",
        "vloerreiniger",
        "wasbeurten",
        "wascapsules",
        "wasm",
        "wasmiddel",
        "wasmiddelcapsules",
        "waspoeder",
        "wasv",
        "wasverz",
        "wasverzachter",
        "woolite",
        "zeebries",
    ),
    "household_supplies": (
        "diepvrieszakken",
        "huisvuilzakken",
        "keukenrol",
        "vuilniszakken",
        "zakdoekjes",
    ),
    "meat_poultry_seafood": (
        "aoste",
        "hespenworst",
        "lende",
        "marcassou",
        "oesters",
        "ontbijtspek",
    ),
    "non_alcoholic_beverages": (
        "aquarius",
        "chaudfontaine",
        "energiedrank",
        "evian",
        "fanta",
        "fuze",
        "granini",
        "ijsthee",
        "limonade",
        "mineraalwater",
        "oasis",
        "pepsi",
        "sportdrank",
        "sprite",
        "volvic",
    ),
    "non_fmcg": (
        "adapter",
        "artline",
        "atoma",
        "autolader",
        "badhanddoek",
        "badjas",
        "badmat",
        "bakpan",
        "balpennen",
        "bestek",
        "bestekset",
        "bluetooth",
        "boekentas",
        "bolsius",
        "braadpan",
        "brother",
        "cadeaukaart",
        "carlinea",
        "chacon",
        "clarysse",
        "clementoni",
        "controller",
        "couteau",
        "dekbed",
        "dekbedovertrek",
        "deksel",
        "dickie",
        "diepvriesdozen",
        "dioptrie",
        "douchehanddoek",
        "draadloze",
        "elastomap",
        "epson",
        "espressomachine",
        "esselte",
        "exacompta",
        "fisher",
        "flanel",
        "fototoestel",
        "gaming",
        "garten",
        "geheugenkaart",
        "geurende",
        "hama",
        "handdoek",
        "hasbro",
        "hdmi",
        "hefboom",
        "herlaadkaart",
        "hoeslaken",
        "hoofdtelefoon",
        "hozelock",
        "inktcartridge",
        "inktpatronen",
        "inktpatroon",
        "kabel",
        "kangourou",
        "kimono",
        "kleurpotloden",
        "koffiezetapparaat",
        "kookpot",
        "kussensloop",
        "laguiole",
        "lannoo",
        "lego",
        "leitz",
        "lepel",
        "lightning",
        "loctite",
        "logitech",
        "mandine",
        "maped",
        "megableu",
        "mepal",
        "metafranc",
        "michelin",
        "microplush",
        "monopoly",
        "moulinex",
        "multistekker",
        "nerf",
        "nintendo",
        "opbergbox",
        "ordner",
        "pagina",
        "panty",
        "patroon",
        "pattex",
        "pelikan",
        "pennenzak",
        "percal",
        "plaid",
        "plakband",
        "playgro",
        "playmobil",
        "playstation",
        "poss",
        "potloden",
        "powerbank",
        "pritt",
        "pyrex",
        "ravensburger",
        "rietjes",
        "ringmap",
        "rowenta",
        "rugzak",
        "samsung",
        "sandisk",
        "schrift",
        "sdhc",
        "servietten",
        "simba",
        "sistema",
        "slakom",
        "sloop",
        "slopen",
        "sony",
        "spaas",
        "stabilo",
        "stofzuiger",
        "sundis",
        "tafellaken",
        "theelichtjes",
        "toys",
        "verjaardagskaars",
        "viquel",
        "voorraaddoos",
        "vtech",
        "vulpen",
        "wielen",
        "wijnglas",
        "zelfklevende",
    ),
    "pantry_cooking": (
        "barilla",
        "basmati",
        "bouillon",
        "calvé",
        "canderel",
        "cecco",
        "conquête",
        "cubetti",
        "devos",
        "didden",
        "ducros",
        "délisoup",
        "elvea",
        "klontjes",
        "knorr",
        "lacroix",
        "langkorrelrijst",
        "lemmens",
        "liebig",
        "maggi",
        "maizena",
        "manna",
        "mayonaise",
        "miracoli",
        "panzani",
        "passata",
        "royco",
        "ruijter",
        "sardienen",
        "soubry",
        "tiense",
        "tomatenblokjes",
        "vandemoortele",
        "vermicelli",
        "verstegen",
        "vetarm",
    ),
    "personal_care": (
        "absodys",
        "aussie",
        "bodyspray",
        "carefree",
        "conditioner",
        "dailies",
        "deospray",
        "discreet",
        "douchecrème",
        "douchegel",
        "droogshampoo",
        "elmex",
        "elnett",
        "elseve",
        "fixatie",
        "haardroger",
        "haarlak",
        "haarspray",
        "haarversieringen",
        "hairspray",
        "incontinentie",
        "inlegkruisjes",
        "intieme",
        "kleuring",
        "listerine",
        "maandverband",
        "maandverbanden",
        "mondspoeling",
        "navulmesjes",
        "ontharingscrème",
        "opzetborstels",
        "palmolive",
        "parodontax",
        "procomfort",
        "rexona",
        "scheersysteem",
        "sensodyne",
        "shamp",
        "shampooing",
        "shoulders",
        "stijltang",
        "styling",
        "taft",
        "tandenborstel",
        "tandpasta",
        "tandvlees",
        "tena",
        "theramed",
        "timotei",
        "transpirant",
        "urineverlies",
        "veet",
        "verbanden",
    ),
    "pet_care": (
        "bifensis",
        "brokjes",
        "catisfactions",
        "cesar",
        "dentastix",
        "friskies",
        "honden",
        "hondensnack",
        "hondensnacks",
        "hondenvoeding",
        "hondenvoer",
        "jumbone",
        "kattenbakvulling",
        "kattensnacks",
        "kattenvoeding",
        "kattenvoer",
        "pedigree",
        "playtime",
        "purina",
        "riga",
        "senior",
        "sheba",
        "sterilcat",
        "versheidszakjes",
        "vitakraft",
        "whiskas",
        "yana",
    ),
    "tobacco": (
        "cigarillo",
        "marlboro",
        "mercator",
    ),
}

# Words that passed the statistics but are not product evidence: retailer and place
# names, colours, and generic adjectives or nouns that only look category-specific
# because of how one retailer files its products.
STOP_TOKENS = frozenset(
    {
        "ademende",
        "afrika",
        "alban",
        "andrã",
        "augustin",
        "automatic",
        "blended",
        "brite",
        "bruisend",
        "campus",
        "carry",
        "carta",
        "cheval",
        "chiné",
        "citroen",
        "clos",
        "colruyt",
        "compressed",
        "creek",
        "cyaan",
        "côtes",
        "dauw",
        "deel",
        "delig",
        "discs",
        "domaine",
        "duurzaam",
        "ecru",
        "effen",
        "estate",
        "florent",
        "gelijnd",
        "georges",
        "geruit",
        "green",
        "gris",
        "gusta",
        "haut",
        "head",
        "hold",
        "interactive",
        "jungle",
        "kist",
        "krachtige",
        "krat",
        "lisa",
        "magenta",
        "maid",
        "malt",
        "marques",
        "marquis",
        "miguel",
        "moisture",
        "nescafã",
        "nomad",
        "ochtend",
        "orange",
        "oreal",
        "rechthoekige",
        "reus",
        "seul",
        "seven",
        "share",
        "sword",
        "tome",
        "trust",
        "turkoois",
        "vanaf",
        "villa",
        "villages",
        "volumia",
        "whitening",
        "willekeurige",
    }
)

TOKEN_CODE = {
    token: code for code, tokens in NAME_KEYWORDS_NL.items() for token in tokens
}
if len(TOKEN_CODE) != sum(len(tokens) for tokens in NAME_KEYWORDS_NL.values()):
    raise ValueError("A name keyword is listed under two categories.")


def name_tokens(name: str | None) -> set[str]:
    """Lower-case words of at least four letters."""
    if not name:
        return set()
    return set(NAME_TOKEN.findall(unicodedata.normalize("NFC", name).lower()))


def classify_name(name: str | None, language: str | None) -> tuple[set[str], set[str]]:
    """Category codes and rule ids that the words of a Dutch product name point to."""
    if language != "nl":
        return set(), set()
    fired = [token for token in name_tokens(name) if token in TOKEN_CODE]
    return {TOKEN_CODE[token] for token in fired}, {f"name:{token}" for token in fired}


def mine_name_keywords(
    decided: Iterable[tuple[str | None, str]],
    *,
    min_support: int = MIN_SUPPORT,
    min_purity: float = MIN_PURITY,
) -> dict[str, tuple[str, int, float]]:
    """Words that identify one category among products whose category is decided.

    ``decided`` yields ``(name, category code)``. Returns word -> (code, products
    carrying the word, share of them in that code). Words in ``STOP_TOKENS`` are
    left out.
    """
    by_token: dict[str, Counter] = defaultdict(Counter)
    for name, code in decided:
        for token in name_tokens(name):
            by_token[token][code] += 1
    vocabulary = {}
    for token, counts in by_token.items():
        support = sum(counts.values())
        code, top = counts.most_common(1)[0]
        if (
            support >= min_support
            and top / support >= min_purity
            and token not in STOP_TOKENS
        ):
            vocabulary[token] = (code, support, top / support)
    return vocabulary
